/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examen2p2_andresnuila;

import java.awt.Color;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;
import java.util.Random;

/**
 *
 * @author enuil
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CrearPC = new javax.swing.JDialog();
        tf_materialBateria = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tf_materialTeclado = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        rb_Tactil = new javax.swing.JRadioButton();
        tf_nSerie = new javax.swing.JFormattedTextField();
        rb_noTactil = new javax.swing.JRadioButton();
        jLabel20 = new javax.swing.JLabel();
        tf_tipoPantalla = new javax.swing.JTextField();
        tf_materialPC = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        sp_nucleosProcesador = new javax.swing.JSpinner();
        tf_tamRAM = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tf_VeloProcesador = new javax.swing.JFormattedTextField();
        tf_marcaRAM = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        tf_tamaDD = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        tf_marcaDD = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        sp_horasBateria = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jy_año = new com.toedter.calendar.JYearChooser();
        jButton1 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        tf_instalacionRAM = new javax.swing.JTextField();
        tf_instalacionDD = new javax.swing.JTextField();
        tf_instalacionBateria = new javax.swing.JTextField();
        tf_instalacionTeclado = new javax.swing.JTextField();
        tf_instalacionPantalla = new javax.swing.JTextField();
        tf_instalacionProcesador = new javax.swing.JTextField();
        tf_colorTeclado = new javax.swing.JTextField();
        tf_colorCompu = new javax.swing.JTextField();
        tactiloNo = new javax.swing.ButtonGroup();
        CrearTecnico = new javax.swing.JDialog();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        tf_nombreTecnico = new javax.swing.JTextField();
        rb_M = new javax.swing.JRadioButton();
        rb_F = new javax.swing.JRadioButton();
        sp_Edad = new javax.swing.JSpinner();
        jb_AgregarTecnico = new javax.swing.JButton();
        MoF3 = new javax.swing.ButtonGroup();
        ensamblaje = new javax.swing.JDialog();
        cb_compus = new javax.swing.JComboBox<>();
        cb_tecnicos = new javax.swing.JComboBox<>();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jb_Ensamblar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        instalacion = new javax.swing.JProgressBar();
        reporte = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        ta_reporte = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        Tecnico = new javax.swing.JMenu();
        agregarTexc = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        Computadora = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        ensamble = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        jLabel17.setText("Material:");

        jLabel6.setText("Disco Duro:");

        jLabel7.setText("Bateria:");

        jLabel18.setText("Color:");

        jLabel8.setText("Teclado:");

        jLabel9.setText("Pantalla:");

        jLabel19.setText("Tactil:");

        jLabel10.setText("Procesador:");

        tactiloNo.add(rb_Tactil);
        rb_Tactil.setText("Si");

        tf_nSerie.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        tactiloNo.add(rb_noTactil);
        rb_noTactil.setText("No");

        jLabel20.setText("Tipo:");

        jLabel11.setText("Tamaño:");

        jLabel21.setText("No. de nucleos:");

        jLabel22.setText("Velocidad:");

        jLabel12.setText("Marca:");

        tf_VeloProcesador.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        jLabel13.setText("Tamaño:");

        jLabel14.setText("Marca:");

        jLabel1.setText("No. de Serie");

        jLabel15.setText("Horas:");

        jLabel2.setText("Año");

        jLabel3.setText("Color");

        jLabel16.setText("Material:");

        jLabel4.setText("Material");

        jLabel5.setText("RAM:");

        jButton1.setText("Añadir");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jLabel23.setText("Tiempo de instalacion (segundos)");

        jLabel24.setText("Tiempo de instalacion (segundos)");

        jLabel25.setText("Tiempo de instalacion (segundos)");

        jLabel26.setText("Tiempo de instalacion (segundos)");

        jLabel27.setText("Tiempo de instalacion (segundos)");

        jLabel28.setText("Tiempo de instalacion (segundos)");

        javax.swing.GroupLayout CrearPCLayout = new javax.swing.GroupLayout(CrearPC.getContentPane());
        CrearPC.getContentPane().setLayout(CrearPCLayout);
        CrearPCLayout.setHorizontalGroup(
            CrearPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CrearPCLayout.createSequentialGroup()
                .addGroup(CrearPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CrearPCLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel17)
                        .addGap(5, 5, 5)
                        .addComponent(tf_materialTeclado, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tf_colorTeclado, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tf_instalacionTeclado, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CrearPCLayout.createSequentialGroup()
                        .addGroup(CrearPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CrearPCLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(tf_nSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(CrearPCLayout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(tf_materialPC, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(CrearPCLayout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel11)
                                .addGap(5, 5, 5)
                                .addComponent(tf_tamRAM, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(jLabel12)
                                .addGap(5, 5, 5)
                                .addComponent(tf_marcaRAM, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)
                                .addComponent(jLabel23)
                                .addGap(39, 39, 39)
                                .addComponent(tf_instalacionRAM, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(CrearPCLayout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel15)
                                .addGap(12, 12, 12)
                                .addComponent(sp_horasBateria, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(jLabel16)
                                .addGap(7, 7, 7)
                                .addComponent(tf_materialBateria, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(98, 98, 98)
                                .addComponent(jLabel27)
                                .addGap(36, 36, 36)
                                .addComponent(tf_instalacionBateria, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(CrearPCLayout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addGroup(CrearPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(CrearPCLayout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(tf_colorCompu, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(CrearPCLayout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(jy_año, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(CrearPCLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13)
                        .addGap(5, 5, 5)
                        .addComponent(tf_tamaDD, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jLabel14)
                        .addGap(5, 5, 5)
                        .addComponent(tf_marcaDD, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(jLabel24)
                        .addGap(39, 39, 39)
                        .addComponent(tf_instalacionDD))
                    .addGroup(CrearPCLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel19)
                        .addGap(1, 1, 1)
                        .addComponent(rb_Tactil)
                        .addGap(0, 0, 0)
                        .addComponent(rb_noTactil)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel20)
                        .addGap(5, 5, 5)
                        .addComponent(tf_tipoPantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tf_instalacionPantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CrearPCLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel21)
                        .addGap(5, 5, 5)
                        .addComponent(sp_nucleosProcesador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel22)
                        .addGap(5, 5, 5)
                        .addGroup(CrearPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CrearPCLayout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(CrearPCLayout.createSequentialGroup()
                                .addComponent(tf_VeloProcesador, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(78, 78, 78)
                                .addComponent(jLabel26)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tf_instalacionProcesador, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        CrearPCLayout.setVerticalGroup(
            CrearPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CrearPCLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(CrearPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CrearPCLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel1))
                    .addComponent(tf_nSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(CrearPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CrearPCLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel2))
                    .addComponent(jy_año, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(CrearPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tf_colorCompu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(CrearPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CrearPCLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel4))
                    .addComponent(tf_materialPC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(CrearPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CrearPCLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel5))
                    .addGroup(CrearPCLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel11))
                    .addGroup(CrearPCLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(tf_tamRAM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CrearPCLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel12))
                    .addGroup(CrearPCLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(tf_marcaRAM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CrearPCLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel23))
                    .addComponent(tf_instalacionRAM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CrearPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(tf_tamaDD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_marcaDD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(CrearPCLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(CrearPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addGroup(CrearPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel24)
                                .addComponent(tf_instalacionDD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(12, 12, 12)
                .addGroup(CrearPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CrearPCLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel7))
                    .addGroup(CrearPCLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel15))
                    .addGroup(CrearPCLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(sp_horasBateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CrearPCLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel16))
                    .addGroup(CrearPCLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(tf_materialBateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CrearPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel27)
                        .addComponent(tf_instalacionBateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15)
                .addGroup(CrearPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CrearPCLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel8))
                    .addGroup(CrearPCLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel17))
                    .addGroup(CrearPCLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(tf_materialTeclado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CrearPCLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(CrearPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(tf_colorTeclado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_instalacionTeclado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(CrearPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CrearPCLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel9))
                    .addGroup(CrearPCLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel19))
                    .addComponent(rb_Tactil)
                    .addComponent(rb_noTactil)
                    .addGroup(CrearPCLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel20))
                    .addGroup(CrearPCLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(tf_tipoPantalla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CrearPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel28)
                        .addComponent(tf_instalacionPantalla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(CrearPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CrearPCLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel10))
                    .addGroup(CrearPCLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel21))
                    .addComponent(sp_nucleosProcesador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(CrearPCLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel22))
                    .addComponent(tf_VeloProcesador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(CrearPCLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(CrearPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(tf_instalacionProcesador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        jLabel29.setText("Nombre");

        jLabel30.setText("Genero");

        jLabel31.setText("Edad");

        MoF3.add(rb_M);
        rb_M.setText("M");

        MoF3.add(rb_F);
        rb_F.setText("F");

        jb_AgregarTecnico.setText("Agregar");
        jb_AgregarTecnico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_AgregarTecnicoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout CrearTecnicoLayout = new javax.swing.GroupLayout(CrearTecnico.getContentPane());
        CrearTecnico.getContentPane().setLayout(CrearTecnicoLayout);
        CrearTecnicoLayout.setHorizontalGroup(
            CrearTecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CrearTecnicoLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(CrearTecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(CrearTecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CrearTecnicoLayout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addGroup(CrearTecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(sp_Edad, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(CrearTecnicoLayout.createSequentialGroup()
                                .addComponent(rb_M)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rb_F))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CrearTecnicoLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(CrearTecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jb_AgregarTecnico)
                            .addComponent(tf_nombreTecnico, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        CrearTecnicoLayout.setVerticalGroup(
            CrearTecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CrearTecnicoLayout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(CrearTecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(tf_nombreTecnico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(CrearTecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(rb_M)
                    .addComponent(rb_F))
                .addGap(32, 32, 32)
                .addGroup(CrearTecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(sp_Edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(jb_AgregarTecnico)
                .addGap(46, 46, 46))
        );

        jLabel32.setText("Computadoras a ensamblar");

        jLabel33.setText("Tecnicos disponibles");

        jb_Ensamblar.setText("Ensamblar");
        jb_Ensamblar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_EnsamblarMouseClicked(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Pieza", "Tiempo de ensamblaje"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout ensamblajeLayout = new javax.swing.GroupLayout(ensamblaje.getContentPane());
        ensamblaje.getContentPane().setLayout(ensamblajeLayout);
        ensamblajeLayout.setHorizontalGroup(
            ensamblajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ensamblajeLayout.createSequentialGroup()
                .addGroup(ensamblajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ensamblajeLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(cb_compus, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90)
                        .addComponent(cb_tecnicos, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ensamblajeLayout.createSequentialGroup()
                        .addGap(287, 287, 287)
                        .addComponent(jb_Ensamblar))
                    .addGroup(ensamblajeLayout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addGroup(ensamblajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE)
                            .addGroup(ensamblajeLayout.createSequentialGroup()
                                .addComponent(jLabel32)
                                .addGap(155, 155, 155)
                                .addComponent(jLabel33))
                            .addComponent(instalacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        ensamblajeLayout.setVerticalGroup(
            ensamblajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ensamblajeLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(ensamblajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_compus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_tecnicos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ensamblajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(jLabel33))
                .addGap(74, 74, 74)
                .addComponent(jb_Ensamblar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(instalacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(93, Short.MAX_VALUE))
        );

        ta_reporte.setColumns(20);
        ta_reporte.setRows(5);
        jScrollPane2.setViewportView(ta_reporte);

        javax.swing.GroupLayout reporteLayout = new javax.swing.GroupLayout(reporte.getContentPane());
        reporte.getContentPane().setLayout(reporteLayout);
        reporteLayout.setHorizontalGroup(
            reporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reporteLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 631, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );
        reporteLayout.setVerticalGroup(
            reporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reporteLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Tecnico.setText("Tecnicos");

        agregarTexc.setText("Agregar");
        agregarTexc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarTexcActionPerformed(evt);
            }
        });
        Tecnico.add(agregarTexc);

        jMenuItem2.setText("Eliminar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        Tecnico.add(jMenuItem2);

        jMenuBar1.add(Tecnico);

        Computadora.setText("Computadoras");

        jMenuItem1.setText("Agregar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        Computadora.add(jMenuItem1);

        jMenuItem3.setText("Eliminar");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        Computadora.add(jMenuItem3);

        jMenuBar1.add(Computadora);

        jMenu3.setText("Ensamblaje");
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });

        ensamble.setText("Nuevo Evento");
        ensamble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ensambleActionPerformed(evt);
            }
        });
        jMenu3.add(ensamble);

        jMenuItem4.setText("Mostrar Reporte de fallos");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 817, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        CrearPC.pack();
        CrearPC.setModal(true);
        CrearPC.setLocationRelativeTo(null);
        CrearPC.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        try {
            String serie = tf_nSerie.getText();
            int año = jy_año.getYear();
            String color = tf_colorCompu.getText();
            String material = tf_materialPC.getText();
            RAM r = new RAM(Integer.parseInt(tf_tamRAM.getText()), tf_marcaRAM.getText(),
                    Integer.parseInt(tf_instalacionRAM.getText()));
            Disco dd = new Disco(Integer.parseInt(tf_tamaDD.getText()), tf_marcaDD.getText(),
                    Integer.parseInt(tf_instalacionDD.getText()));
            Bateria b = new Bateria(Integer.parseInt(sp_horasBateria.getValue().toString()),
                    tf_materialBateria.getText(), Integer.parseInt(tf_instalacionBateria.getText()));
            Teclado t = new Teclado(tf_materialTeclado.getText(), tf_colorTeclado.getText(),
                    Integer.parseInt(tf_instalacionTeclado.getText()));
            String tactil = "";
            if (rb_Tactil.isSelected()) {
                tactil = "TACTIL";
            } else if (rb_noTactil.isSelected()) {
                tactil = " NO TACTIL";
            }
            Pantalla p = new Pantalla(tactil, tf_tipoPantalla.getText(), Integer.parseInt(tf_instalacionPantalla.getText()));
            Procesador pr = new Procesador(Integer.parseInt(sp_nucleosProcesador.getValue().toString()),
                    Double.parseDouble(tf_VeloProcesador.getText()), Integer.parseInt(tf_instalacionProcesador.getText()));
            Computadora c = new Computadora(serie, material, color, año, r, dd, b, t, p, pr);
            c.getPartes().add(r);
            c.getPartes().add(dd);
            c.getPartes().add(b);
            c.getPartes().add(t);
            c.getPartes().add(p);
            c.getPartes().add(pr);
            pcs.add(c);
            adminCompus ac = new adminCompus("./Computadoras.dna");
            ac.cargarArchivo();
            ac.getComputadoras().add(c);
            ac.escribirArchivo();
            JOptionPane.showMessageDialog(null, "SE HA CREADO EXITOSAMENTE");
            tf_nSerie.setText("");
            tf_tamRAM.setText("");
            tf_marcaRAM.setText("");
            tf_instalacionRAM.setText("");
            tf_tamaDD.setText("");
            tf_marcaDD.setText("");
            tf_instalacionDD.setText("");
            tf_materialBateria.setText("");
            tf_instalacionBateria.setText("");
            tf_materialTeclado.setText("");
            tf_instalacionTeclado.setText("");
            tf_tipoPantalla.setText("");
            tf_instalacionPantalla.setText("");
            tf_VeloProcesador.setText("");
            tf_instalacionProcesador.setText("");
        } catch (IOException ex) {
            ex.printStackTrace();
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jb_AgregarTecnicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_AgregarTecnicoMouseClicked
        try {
            String nombre = tf_nombreTecnico.getText();
            String genero = "";
            if (rb_M.isSelected()) {
                genero = "M";
            } else if (rb_F.isSelected()) {
                genero = "F";
            }
            int edad = Integer.parseInt(sp_Edad.getValue().toString());
            Tecnico t = new Tecnico(nombre, genero, edad);
            adminTecnicos at = new adminTecnicos("./Tecnicos.txt");
            at.cargarArchivo();
            at.getTecnicos().add(t);
            at.escribirArchivo();
            tf_nombreTecnico.setText("");
            JOptionPane.showMessageDialog(null, "SE HA AGREGADO EXITOSAMENTE");
            tecnicos.add(t);
        } catch (IOException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jb_AgregarTecnicoMouseClicked

    private void agregarTexcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarTexcActionPerformed
        CrearTecnico.pack();
        CrearTecnico.setModal(true);
        CrearTecnico.setLocationRelativeTo(null);
        CrearTecnico.setVisible(true);
    }//GEN-LAST:event_agregarTexcActionPerformed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed


    }//GEN-LAST:event_jMenu3ActionPerformed

    private void ensambleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ensambleActionPerformed
        try {
            cb_compus.removeAllItems();
            cb_tecnicos.removeAllItems();
            DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_compus.getModel();
            adminCompus ac = new adminCompus("./Computadoras.dna");
            ac.cargarArchivo();
            for (int i = 0; i < ac.getComputadoras().size(); i++) {
                modelo.addElement(ac.getComputadoras().get(i));
            }
            cb_compus.setModel(modelo);

            DefaultComboBoxModel modelo2 = (DefaultComboBoxModel) cb_tecnicos.getModel();
            adminTecnicos at = new adminTecnicos("./Tecnicos.txt");
            at.cargarArchivo();
            for (int i = 0; i < at.getTecnicos().size(); i++) {
                modelo2.addElement(at.getTecnicos().get(i));
            }
            cb_tecnicos.setModel(modelo2);
            ensamblaje.pack();
            ensamblaje.setModal(true);
            ensamblaje.setLocationRelativeTo(null);
            ensamblaje.setVisible(true);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_ensambleActionPerformed

    private void jb_EnsamblarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_EnsamblarMouseClicked
        OrdenEnsamblaje o = new OrdenEnsamblaje((Computadora) cb_compus.getSelectedItem(), (Tecnico) cb_tecnicos.getSelectedItem());
        Ensamblaje e = new Ensamblaje(o, jTable1, instalacion);
        Thread proceso = new Thread(e);
        proceso.start();
    }//GEN-LAST:event_jb_EnsamblarMouseClicked

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        try {
            adminCompus ac = new adminCompus("./Computadoras.dna");
            String aux = "";
            ac.cargarArchivo();
            for (int i = 0; i < ac.getComputadoras().size(); i++) {
                aux += i + "->" + ac.getComputadoras().toString() + "\n";
            }
            JOptionPane.showMessageDialog(null, aux);
            int eli = Integer.parseInt(JOptionPane.showInputDialog("ingrese el indice a eliminar"));
            ac.getComputadoras().remove(eli);
            ac.escribirArchivo();
            JOptionPane.showMessageDialog(null, "eliminado exitosamente");
        } catch (IOException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        try {
            adminTecnicos at = new adminTecnicos("./Tecnicos.txt");
            String aux = "";
            at.cargarArchivo();
            for (int i = 0; i < at.getTecnicos().size(); i++) {
                aux += i + "->" + at.getTecnicos().toString() + "\n";
            }
            JOptionPane.showMessageDialog(null, aux);
            int eli = Integer.parseInt(JOptionPane.showInputDialog("ingrese el indice a eliminar"));
            at.getTecnicos().remove(eli);
            at.escribirArchivo();
            JOptionPane.showMessageDialog(null, "eliminado exitosamente");
        } catch (IOException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        File fichero = new File("./Bitacora de fallos.txt");
        FileReader fr = null;
        if (fichero.isFile()) {
            try {
                fr = new FileReader(fichero);
                BufferedReader br = new BufferedReader(fr);
                String linea = "";
                while ((linea = br.readLine()) != null) {
                    ta_reporte.append(linea);
                    ta_reporte.append("\n");
                }
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        reporte.pack();
        reporte.setModal(true);
        reporte.setLocationRelativeTo(null);
        reporte.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Computadora;
    private javax.swing.JDialog CrearPC;
    private javax.swing.JDialog CrearTecnico;
    private javax.swing.ButtonGroup MoF3;
    private javax.swing.JMenu Tecnico;
    private javax.swing.JMenuItem agregarTexc;
    private javax.swing.JComboBox<String> cb_compus;
    private javax.swing.JComboBox<String> cb_tecnicos;
    private javax.swing.JDialog ensamblaje;
    private javax.swing.JMenuItem ensamble;
    private javax.swing.JProgressBar instalacion;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jb_AgregarTecnico;
    private javax.swing.JButton jb_Ensamblar;
    private com.toedter.calendar.JYearChooser jy_año;
    private javax.swing.JRadioButton rb_F;
    private javax.swing.JRadioButton rb_M;
    private javax.swing.JRadioButton rb_Tactil;
    private javax.swing.JRadioButton rb_noTactil;
    private javax.swing.JDialog reporte;
    private javax.swing.JSpinner sp_Edad;
    private javax.swing.JSpinner sp_horasBateria;
    private javax.swing.JSpinner sp_nucleosProcesador;
    private javax.swing.JTextArea ta_reporte;
    private javax.swing.ButtonGroup tactiloNo;
    private javax.swing.JFormattedTextField tf_VeloProcesador;
    private javax.swing.JTextField tf_colorCompu;
    private javax.swing.JTextField tf_colorTeclado;
    private javax.swing.JTextField tf_instalacionBateria;
    private javax.swing.JTextField tf_instalacionDD;
    private javax.swing.JTextField tf_instalacionPantalla;
    private javax.swing.JTextField tf_instalacionProcesador;
    private javax.swing.JTextField tf_instalacionRAM;
    private javax.swing.JTextField tf_instalacionTeclado;
    private javax.swing.JTextField tf_marcaDD;
    private javax.swing.JTextField tf_marcaRAM;
    private javax.swing.JTextField tf_materialBateria;
    private javax.swing.JTextField tf_materialPC;
    private javax.swing.JTextField tf_materialTeclado;
    private javax.swing.JFormattedTextField tf_nSerie;
    private javax.swing.JTextField tf_nombreTecnico;
    private javax.swing.JTextField tf_tamRAM;
    private javax.swing.JTextField tf_tamaDD;
    private javax.swing.JTextField tf_tipoPantalla;
    // End of variables declaration//GEN-END:variables
    private ArrayList<Computadora> pcs = new ArrayList();
    private ArrayList<Tecnico> tecnicos = new ArrayList();
    static Random r = new Random();
}
